### ISSUE TITLE
How to show an image in excel cell

### ISSUE THREAD

**Issue by navneetccna** [Ticketpark/HtmlPhpExcel#1]
I am using html with a image in a table cell but it is not visible in excel

Is there any way to add image in excel as i know phpexcel do that ?

Can we set image in cell backgroud using style ?

**Comment by sprain** [comment]
Using images in an excel file is currently not actively supported by this library. I suppose there is not a very widesprad need for this feature. However, you are welcome to contribute a pull request on this topic if you like.

**Comment by navneetccna** [comment]
yes i would like too as it is very good to convert html to excel and i think html is very esay to design and image like logo in report is very much essintial and also as phpexcel library is supporting the same feature but it is very complicated using that library. i like libraray and easy to use.
