### ISSUE TITLE
How can I add a border color?

### ISSUE THREAD

**Issue by nFnK** [Ticketpark/HtmlPhpExcel#10]
How can I add a border color?
for example : 1px solid #000

**Comment by romeci** [comment]
Hi, I had the same question, but I managed to solve it, here's an example!

`_excel-styles='{"borders" : {"allBorders" : {"borderStyle" : "medium", "color" : {"argb" : \"FF000000\"}}}}'`

BorderStyle can use 'thin' for lightweight as well.
