### ISSUE TITLE
Package phpoffice/phpexcel is abandoned

### ISSUE THREAD

**Issue by icyz** [Ticketpark/HtmlPhpExcel#11]
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

Are you planning to update?
Thank you.

**Comment by sprain** [comment]
Moving to `phpoffice/phpspreadsheet` would be good.

Here is a migration guide for anybody who would like to contribute to this:
https://phpspreadsheet.readthedocs.io/en/develop/topics/migration-from-PHPExcel/

**Comment by icyz** [comment]
Link is broken :-)

**Comment by sprain** [comment]
New link :)
https://phpspreadsheet.readthedocs.io/en/latest/topics/migration-from-PHPExcel/
