### ISSUE TITLE
[Feature Request] Make a cell clickable, adding `_excel-link` attribute

### ISSUE THREAD

**Issue by flashios09** [Ticketpark/HtmlPhpExcel#16]
hi @sprain,
What about adding a new `_excel-link` attribute [to make a clickable cell](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#change-a-cell-into-a-clickable-url), maybe something like this:
```html
<table>
    <tr>
        <td _excel-link="mailto:contact@domain.com">contact@domain.com</td>
        <td _excel-link="https://www.domain.com">www.domain.com</td>
        <td _excel-link="sheet://'Sheetname'!A1">Sheetname</td>
    </tr>
</table>
```
With **PhpSpreadsheet**, we need to do:
```php
$objPHPExcel->getActiveSheet()->setCellValue('E26', 'www.phpexcel.net');
$objPHPExcel->getActiveSheet()->getCell('E26')->getHyperlink()->setUrl("sheet://'Sheetname'!A1");
```
So all we have to do is to modify [`HtmlPhpExcel::createExcel`](https://github.com/Ticketpark/HtmlPhpExcel/blob/master/lib/HtmlPhpExcel/HtmlPhpExcel.php#L220) method:
```php
private function createExcel(): void
{
    // ...
   foreach($row->getCells as $cell) {
       // Set value 
       // ...
      
      // Set Url
      $cellLink = $cell->getAttribute('_excel-link');
      if ($cellLink) {
          // maybe we need to verify the link before !
          if ($this->_isValidUrl($cellLink)) {
                $excelWorksheet->getCell($excelCellIndex)->getHyperlink()->setUrl($cellLink);
          }
      }
      
      // Merge cells
     // ...
  }
```

I can create a pull request and add some tests too :)

**Comment by sprain** [comment]
> I can create a pull request and add some tests too

You are welcome to do so :)

**Comment by sprain** [comment]
Done in #34 for v1.
Supported by default by styles in v2.
