### ISSUE TITLE
Support UTF8

### ISSUE THREAD

**Issue by bakhadev** [Ticketpark/HtmlPhpExcel#17]
Hi, utf8 is not supported.

**Comment by sprain** [comment]
You are likely looking for this:

```php
$htmlPhpExcel
  ->utf8EncodeValues() // or utf8DecodeValues()
  ->process()
  ->output();
```

If this does not work, feel free to re-open the issue with some explanation on the output that you get.

**Comment by tarwaghila** [comment]
I got the same issue.

The solution was to convert encoding to UTF-8 when parsing the HTML.

At the class `Ticketpark\HtmlPhpExcel\Parser\Parser`

Function `parse`

before loading the `HTML` into the  `\DOMDocument()`, convert `HTML` to the internal encoding


        $dom = new \DOMDocument();
        
        //Convert to the internal encoding
        $this->html = mb_convert_encoding($this->html, 'HTML-ENTITIES', iconv_get_encoding());
        
        $dom->loadHTML($this->html);`
