### ISSUE TITLE
Html-table-string error on unix

### ISSUE THREAD

**Issue by c-key** [Ticketpark/HtmlPhpExcel#4]
When processing a HTML-table string (with 48736 chars) in an Unix-System there is the following mistake:
_is_file(): File name is longer than the maximum allowed path length on this platform (4096)_
for file: ticketpark/htmlphpexcel/lib/HtmlPhpExcel/Parser/Parser.php
In what reason?
Can be fixed?

**Comment by c-key** [comment]
Other projects have the same error, look here https://github.com/nette/nette/commit/4bc67e38f58f99ea9e5ca4322f8808080adfb8ac
Maybe this will be a possible fix.

**Comment by sprain** [comment]
@c-key Thanks for opening an issue. You are very welcome to try the fix and open an pull request if it works.

**Comment by c-key** [comment]
Hello, I have tried the fix and it worked.

**Comment by sprain** [comment]
Fixed in #19
