### ISSUE TITLE
Problem with diacritics

### ISSUE THREAD

**Issue by JurajG007** [Ticketpark/HtmlPhpExcel#43]
It is not possible to properly convert strings with diacritics.

Try convert this string written in UTF-8: 
`$html = <table><tr><th>Číslo</th><th>Ťukyťuk</th></tr><tr><td>Čačane</td><td>Value B</td></tr></table>`

![image](https://github.com/Ticketpark/HtmlPhpExcel/assets/6041170/7481c731-78ed-4d64-b6e7-94556fd80902)

**Comment by sprain** [comment]
Make sure your content is utf8-encoded.

See example:

https://github.com/Ticketpark/HtmlPhpExcel/blob/567fa60a159bef1013d451ccae13941d9e20fb25/example/example.html#L1

https://github.com/Ticketpark/HtmlPhpExcel/blob/567fa60a159bef1013d451ccae13941d9e20fb25/example/example.html#L53

Feel free to re-open this task with more information if this does not help.

**Comment by JurajG007** [comment]
Ok, my fault as I sent to class constructor "pure" string with tables only.
Now it is working fine.  Thank you for your quick response!
