### ISSUE TITLE
How to merge two cells

### ISSUE THREAD

**Issue by xheisenbugx** [Ticketpark/HtmlPhpExcel#5]
Hi, I am testing the examples, but i want to merge two cells like colspan attribute in html.

**Comment by sprain** [comment]
Sorry, this is currently not supported by this library. 

You are welcome to propose a solution in a pr. Using rowspan / colspan in excel combined with PhpExcels mergeCells() would make a nice match.

**Comment by xheisenbugx** [comment]
Thanks for the workaround :)
