### ISSUE TITLE
syntax error, unexpected '?' in 

### ISSUE THREAD

**Issue by fantazamazul** [Ticketpark/HtmlPhpExcel#9]
Hi, i have install Ticketpark/HtmlPhpExcel according the doc, but when run my code, i have this error. 
Parse error: syntax error, unexpected '?' in vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php on line 240

**Comment by sprain** [comment]
You seem to have altered the code of the file `ArrayCollection.php`. The problem of this is very likely outside of this library.
